### ISSUE TITLE
Functional - iOS - "Enforcement" Screen Not Following Standard for Colors

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#102]
While testing the "Enforcement" screen, we noticed that the words "Yes" and "No" did not use color to help people notice them as all the other screen did. On other screens the word "Yes" was green and the word "No" was red.

You should not only denote something with color, but the application is using words but wanted it to be constant across the application.

**Comment by sanganalakshay** [comment]
This is the way it has always been and the current version on App Store behaves the same way. 
We can change the logic to show the color as you outlined if required/requested.

**Comment by jfc3-dol** [comment]
The issue of not having the word "Yes" was green, and the word "No" was red to be consistent throughout the application is still an outstanding issue.

**Comment by clguidi** [comment]
John, this could be misleading for users as the enforcement section has different standards from the legal framework section. As this is not an accessibility issue, please close this issue. Thank you.

**Comment by clguidi** [comment]
John, please close this issue. We will not be addressing it as we state in the methodology section that the red/green for No/Yes is applicable only to the Legal Framework and Coordinating Mechanisms section. If we apply the same formatting on the enforcement section then it would impact methodology. Thank you.

**Comment by jfc3-dol** [comment]
@KyleLivingstonDOL,

Looking through old mail in the "Other" tab, I noticed this issue was there and still open.

I am doing a bit of e-mail clean up, so I'm going to close this issue.
