### ISSUE TITLE
gitignore .DS_Store file

### ISSUE THREAD

**Issue by anselmbradford** [USDepartmentofLabor/Child-Labor#103]
Repo includes [`.DS_Store` file](https://github.com/USDepartmentofLabor/Child-Labor/blob/master/.DS_Store) that will be automatically created by the OS and is not needed in the repo. Repository root directory should include `.gitignore` text file with the following content:

```
.DS_Store
```

**Comment by jfc3-dol** [comment]
@harpreetsdev @pbhatt17 @Abychalil

I have not idea what this is, and likely not related to accessibility.

So if you want, you can close it if that makes sense.

**Comment by anselmbradford** [comment]
Hi @jfc3-dol, it means this directory was created on a Mac and contains a file specific to that operating system. All that needs to be done is https://github.com/USDepartmentofLabor/Child-Labor/blob/master/.DS_Store needs to be deleted and a text file file, `.gitignore`, needs to be created with the content `.DS_Store`. This was done in https://github.com/USDepartmentofLabor/Child-Labor/commit/c76fcd46ccb844204c37e45f3c275579a5e9526d#diff-a084b794bc0759e7a6b77810e01874f2, but the `.DS_Store` file was not removed at the same time.

**Comment by anselmbradford** [comment]
Here this can just be merged and this issue closed --> https://github.com/USDepartmentofLabor/Child-Labor/pull/130

**Comment by jfc3-dol** [comment]
@anselmbradford 

Thanks for the clarification of what the issue was about and that I was right in it not being an accessibility-related issue I need to review.

**Comment by anselmbradford** [comment]
@pbhatt17 @LeHaine @akshaysanganal Are you able to merge https://github.com/USDepartmentofLabor/Child-Labor/pull/137 and close this issue?

**Comment by anselmbradford** [comment]
Hi, bump on this. #137 is a super easy PR. Can someone with rights in this repo merge it? @pbhatt17 @LeHaine @akshaysanganal

**Comment by anselmbradford** [comment]
Actually, scratch that. I see it was done in https://github.com/USDepartmentofLabor/Child-Labor/commit/9c3b6766db398506a3637886df87f2481b22be43
