### ISSUE TITLE
Fucntional - iOS - More Info Screen - Last Four Links on Screen Get Page Not Found Error (404)

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#113]
While testing the "More Info" screen I noticed the last four links on this screen get a page not found error (404).

**Comment by trevitalgit** [comment]
in More info, three links were updated as followed per Claudia email.

Child Labor Report
https://www.dol.gov/sites/dolgov/files/ILAB/child_labor_reports/tda2017/ChildLaborReport.pdf
Placeholder for the moment
Child and Forced Labor List of Goods
https://www.dol.gov/sites/dolgov/files/ILAB/ListofGoods.pdf
Remains the same, we don't publish update this year
Forced Child Labor List of Products
https://www.dol.gov/sites/dolgov/files/ILAB/EO_Report_2014.pdf

Foreword link is working. If you need to update it, let me know.

The last link "New Comply Chain App" is not working. Please give me a new link for that.

**Comment by jfc3-dol** [comment]
The following is what I see for the last four links on the screen.

- **Child Labor Report** -2017 Place holder report
- **Child and Forced Labor List of Goods** - 2018 list of goods. I noticed that the Comply Chain screenshot is from last years application with the cog/wheel.
- **Forced Child Labor List of Products** - shows older version
- **NEW: Comply Chain App** - page not found

**Comment by clguidi** [comment]
Hi John, 
I've replied to your notes. Please review the issue in the latest app build and close this issue when you have reviewed and verified it is no longer present. Thank you.

Child Labor Report -2017 Place holder report - will remain the same in this build, but will be updated with the last release when we finally have the 2018 magazine PDF

•Child and Forced Labor List of Goods - 2018 list of goods. I noticed that the Comply Chain screenshot is from last years application with the cog/wheel. - We cannot update the previous year's 2018 TVPRA magazine to address Comply Chain's former icon. That is not an efficient use of resources. 

•Forced Child Labor List of Products - shows older version - This is the latest version we have. We do not publish this report on a regular basis. It is only updated when there is an addition or removal or another significant update.

•NEW: Comply Chain App - page not found - This has been addressed.

**Comment by jfc3-dol** [comment]
@clguidi,

I didn't realize most of those documents are not updated regularly.

The Comply Chain App link now works and goes to a page about the application.

I did notice that the screenshot on the page shows the old application. When you have time, you might want to send the web team an updated image, so the users don't think they have the wrong version that is once the new applicaiotn goes live.

I'm closing the issue.
