### ISSUE TITLE
Functional - iOS - Country - Report PDF Link is Showing 2017 PDF Instead of 2018 Content

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#115]
On the countries, I looked at randomly the "Report PDF" link is showing PDF content from 2017  instead of 2018, which is what I was expecting to see.

Please see the attached screenshot as an example.

![sweat and toil - ios - Turkey - reprot pdf showing 2017 content instead of 2018 as expected](https://user-images.githubusercontent.com/10423487/63039048-76d8d280-be90-11e9-8cc4-de652a74786d.png)

**Comment by clguidi** [comment]
Thank you John. We do not have the newest PDFs yet so you will find this issue in all the countries. Please do not open new tickets. We are fully aware of the issue and will address them as soon as we have the latest PDFs.

**Comment by jfc3-dol** [comment]
@clguidi,

I figured one issue would be enough to make sure you knew the report PDFs were still from last year. 

Years ago, while testing the team did not realize the files hadn't been updated, so they were thankful. Since no one mentioned it to me, I went with safe than sorry by mentioning it.

**Comment by jfc3-dol** [comment]
I'm still seeing the "Report"PDFs" pointing documents that start with 2017 instead of 2018.

Please see the attached screenshots.

India - Report PDF - 2017

![comply chain - ios - report pdf - india 2017](https://user-images.githubusercontent.com/10423487/64735322-57948b80-d4b6-11e9-94cc-3382ca9b8cd2.png)

Turkey - Report PDF - 2017

![comply chain - ios - report pdf - turkey 2017](https://user-images.githubusercontent.com/10423487/64735324-57948b80-d4b6-11e9-8a93-15fce021a5ae.png)

**Comment by clguidi** [comment]
Hi John, this is issue has been resolved now that we finally have the 2018 PDFs. Please download the latest build to test and please close as soon as you can. Thank you.

**Comment by jfc3-dol** [comment]
I have looked at India, Turkey, and other "Report PDF" documents and they now point to the 2018 version. So I'm going to close the issue.
