### ISSUE TITLE
Functional - iOS - Enforcement - For Brazil Why is There 56 after Answers

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#116]
While looking at the "Labor" tab on the Enforcement screen for Brazil, I notice "(56)" after almost every answer that had something after it but one which was 59. The "Criminal" tab had different numbers while on other screens those numbers related to children's ages or some other code that was defined at the bottom of the screen and there is nothing on this page. I guess that the application is displaying the number from the record and not converting it to other text or special characters that have given meaning.

Please see the attached screenshots to show what I'm talking about.

Labor tab

![sweat and toil - ios - brazil - enforcement screen labor tab showing 56 after most answers with no reason why](https://user-images.githubusercontent.com/10423487/63045833-316fd180-be9f-11e9-94bb-1a49ccd75f3c.png)

Criminal tab

![sweat and toil - ios - brazil - enforcement screen criminal tab showing other numbers besides most 56](https://user-images.githubusercontent.com/10423487/63045832-316fd180-be9f-11e9-8597-e16e231027f0.png)

**Comment by jfc3-dol** [comment]
Ecuador has mostly "2" and "10", while Belize has "3" between the brackets ( ). Having the same number after dollars or other numbers is confusing and even when they are after "Yes" or "No".

**Comment by jfc3-dol** [comment]
Why does Nicaragua have two number in brackets( )?

**Comment by clguidi** [comment]
Thank you John, that is due to a quirk with the new data format and we will address that before the release.

**Comment by jfc3-dol** [comment]
@clguidi,
Okay, with having the issue open it will remind me to check it once fixed and then close the issue after reviewing it's been corrected.

**Comment by jfc3-dol** [comment]
I have looked at the countries mentioned above, and they do not have any extra numbers like those mentioned above, so I'm going to close the issue.
