### ISSUE TITLE
Fucntional - iOS - Enhancement - Labor Inspector Funding Display Issue

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#117]
While looking at different countries "Enhancement" screen for the "Labor" tab, I noticed the "Labor Inspector Funding" text is over lapping with the dollar number when in portrait mode on OPAs iPhone 7.

**Comment by clguidi** [comment]
Please provide a screenshot.

**Comment by jfc3-dol** [comment]
@clguidi,

It will take a bit to find which country I was looking at on our iPhone since I, for some reason didn't mention it in the issue.

**Comment by jfc3-dol** [comment]
Can't seem to find one now, but will keep looking. Maybe it was a typo, or the font size was larger that was causing the issue.

**Comment by clguidi** [comment]
Thank you John. If you are not able to recreate and document the issue, could you please close this issue?

**Comment by jfc3-dol** [comment]
I'm going to close this issue and if I find it again, I will re-open it or start a new one.
