### ISSUE TITLE
Change app name to "Sweat & Toil"

### ISSUE THREAD

**Issue by skeeJay** [USDepartmentofLabor/Child-Labor#15]

**Comment by MikePulsiferDOL** [comment]
Do you realize that changing the app name complicates matters and will end up requiring a whole new review period for the beta of the app?

**Comment by skeeJay** [comment]
No, I'm not sure I understand. This was a decision by ILAB which I wasn't part of, but I think it depends what name you mean. The first is the bundle identifier of the app, which can remain the same.....no one has any issue with the Xcode project name or the bundle identifier of the app remaining the way it is. The request is to customize two things: the "long form" name under which the app appears in the App Store, which is its own setting in the submission process I believe, and the "display name" under the icon on the home screen, which is its own property in the plist in Xcode.

Even if changing the display name of the app requires a new review period for the beta (which is all this commit does) I think we've built in enough time for it. The first review of the beta took about 48 hours. If I get you the new beta on Monday, the hope is that ILAB can begin reviewing on Wednesday.

**Comment by MikePulsiferDOL** [comment]
Historically, changing the app name meant actually creating a new app.  It was metadata that couldn't be changed.  I'll see if that has changed since then.  Also, don't bank on 2 days.  It all depends on a) when the bundle of apps are picked up by the reviewer and b) which order they do them.

**Comment by skeeJay** [comment]
Which app name does that apply to? All I've changed so far is the display
name property of the plist, so if you don't change any other metadata, we
should be fine, right?

**Comment by MikePulsiferDOL** [comment]
I'm actually talking about what's displayed in the App Store.  This is something I went through with one of my personal apps a few years ago.  I'll try it and see if they changed this.

**Comment by skeeJay** [comment]
We don't have to change the App Store name for the purposes of the
beta—this task was just to change the home screen display name.

There will be a final decision about the App Store name coming at a later
time, but since we haven't submitted to the App Store at all yet and there
will be a 10-day review period anyway, I assume this won't be a problem for
us.

**Comment by MikePulsiferDOL** [comment]
GD.  I said I'd try.  I just did.  It let me do it.  Moving on...

**Comment by skeeJay** [comment]
Okay, thanks.
