### ISSUE TITLE
Suggested action table cells sometimes don't dynamically expand to show the whole label

### ISSUE THREAD

**Issue by skeeJay** [USDepartmentofLabor/Child-Labor#43]
This seems to be related to the redraw.......if you scroll it out of view and back into view, it's sized differently. There may be a way to force a redraw on load.

**Comment by skeeJay** [comment]
This only seems to be occurring when building from Xcode 6 and not Xcode 7.

**Comment by jfc3-dol** [comment]
Nothing seems to have been done for this issue, or it corrected itself. So I'm closing it.
