### ISSUE TITLE
Add Link to Country Web Page to Country Screens

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#50]
Since iOS and Android do not read the structure of PDFs currently can you please add a link to the countries web page so people using assistive technologies like screen readers(VoiceOver) can have a more accessible experience as long as they have connection to the internet.

For more information about this problem you can look at issues #48 and #49 for issues found when only having full information as a PDF, along with the text being too small to read on an iPhone.

Below is some background information on why iOS and Android currently don't read PDFs correctly.

I asked my Twitter followers, and Sam Joehl (@mixolydian) responded with an article that states iOS and Android PDF readers on mobile devices do not currently read PDF structure (headings, lists, tables, etc.) correctly.

The article is - [PDF Accessibility on Mobile Devices](http://www.ssbbartgroup.com/blog/pdf-accessibility-on-mobile-devices/) by SSB BART Group's Jonathan Avila

and here is a short excerpt from it:
# What PDF features are generally not accessible?

Structural information such as the presence of headings, lists, tables, and images are not indicated using the default iOS or Android PDF viewer installed with Google Drive or Adobe Reader. In addition, the ability to navigate between units such as lines, paragraphs, headings, lists, etc. are not available.

**Comment by carolynhuang** [comment]
Please check latest version. This feature has been added.

**Comment by jfc3-dol** [comment]
@carolynhuang,

What was the fix for this issue?

Did you add links to web pages instead of the having the PDFs in the application which VoiceOver cannot read all the proper tagged structure?

**Comment by sanganalakshay** [comment]
link to the webpages have been added

**Comment by carolynhuang** [comment]
@jfc3-dol Just for clarification, it is on every country html page. The last link on the bottom, "Country Webpage" below Report PDF.

**Comment by jfc3-dol** [comment]
@carolynhuang and @sanganalakshay,

I looked at a random sampling of the country pages and noticed the "Country Webpage" link below the "Report PDF" goes to the proper web page for each country.

I also looked at a few of those web pages quickly and found accessibility issues such as a user cannot get to the "Expand All" link/button with a keyboard to open all the closed sections below. Along with missing/incorrect LABEL for the two drop-down lists and a few other things.

The web pages should have the accessibility issues corrected too for those coming from the native application and those going directly to the web pages.

**Comment by jfc3-dol** [comment]
@carolynhuang and @sanganalakshay,

I looked at a random sampling of the country pages and noticed the "Country Webpage" link below the "Report PDF" goes to the proper web page for each country.

I also looked at a few of those web pages quickly and found accessibility issues such as a user cannot get to the "Expand All" link/button with a keyboard to open all the closed sections below. Along with missing/incorrect LABEL for the two drop-down lists and a few other things.

The web pages should have the accessibility issues corrected too for those coming from the native application and those going directly to the web pages.

**Comment by carolynhuang** [comment]
Thanks for letting us know about this, John. Unfortunately, correcting accessibility issues within the DOL webpage is beyond the scope of the app.  We have added the feature as you requested, so this issue should be closed.

**Comment by jfc3-dol** [comment]
@carolynhuang,

As part of next years test plan will be to test the web pages or at least a sampling of some of the country, goods, etc. pages and the connecting pages for accessibility issues.

I'm going to create an issue or two, so we have a reminder for next year because these pages should have been tested.

**Comment by jfc3-dol** [comment]
Country pages do have a link to the countries web page which is more accessible than the PDF and an alternative to the PDF.

Closing issue.
