### ISSUE TITLE
Release 3D-Touch 

### ISSUE THREAD

**Issue by neilneyman** [USDepartmentofLabor/Child-Labor#51]
@skeeJay Can you please provide some information about what part of the app was updated with 3D-Touch capabilities?  I need to provide some information to the QA team about what they're looking for in testing.

Thanks!

**Comment by skeeJay** [comment]
I added "quick action" support to the home screen icon. It made sense to link to the 3 main screens of the app. Screenshot below. It doesn't affect the experience inside the app at all and shouldn't affect older iPhones at all.

![img_1828](https://cloud.githubusercontent.com/assets/506096/13508516/476c0326-e155-11e5-8b1d-3e335b17cb16.PNG)

**Comment by jfc3-dol** [comment]
Closing issue since it looks like 3-D touch is not on the icon anymore.
