### ISSUE TITLE
Multiple constraints alerts in main.storyboard

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Child-Labor#52]
![screen shot 2016-05-31 at 9 56 49 am](https://cloud.githubusercontent.com/assets/1970829/15676892/0a33652e-2716-11e6-9942-abe3bb73f3f5.png)

**Comment by aquilent-dgemoets** [comment]
These will be largely resolved in the upcoming beta.  We just hadn't addressed iOS constraints yet.  There is still one "Scene is unreachable" warning that has a mysterious cause but isn't causing any problems.

**Comment by aquilent-dgemoets** [comment]
The remaining warnings have been addressed.
