### ISSUE TITLE
Test with a small device (iPhone 4/5)

### ISSUE THREAD

**Issue by aquilent-dgemoets** [USDepartmentofLabor/Child-Labor#60]
The beta released 11-August-2016 was not tested on a small device (iPhone 4/5).

When tested on an iPhone 4 simulator, on the Pakistan Legal Standards page, the "Pakhtunkhwa (KP)" in "Khyber Pakhtunkhwa (KP)" doesn't initially appear, but then appears when you scroll down and scroll back up.

**Comment by aquilent-dgemoets** [comment]
The latest beta (9/9) has been tested with a small device.

The only outstanding issues are:
- The main screen's background image is clipped by the list at the top of the screen such that the boy's head isn't fully visible unless you scroll the image upward.
- In the Enforcement screen, after changing tabs, the territory names do not wrap-- so longer names get truncated.
- In the Info screen, "Child and Forced Labor List of Goods" doesn't wrap and is displayed as "Child and Forced Labor List of Go..."

These remaining issues will be prioritized by ILAB as we approach final release.

**Comment by aquilent-dgemoets** [comment]
The last item has been fixed-- please verify.
The second-to-last item (territory names not wrapping):  I think this happens on iOS 8.x, but not 9.x.

**Comment by aquilent-dgemoets** [comment]
The first item (clipped background image) has been fixed in the 10/25 beta version.

The second-to-last item (territory names not wrapping) is confirmed not to happen in modern iOS versions (9.x or later).  Less than 5% of devices use iOS 8.x.

**Comment by jfc3-dol** [comment]
Closing issue because I have not seen any problems with using the smaller phones.
