### ISSUE TITLE
Functional - Goods Search Not in Alphabetical Order

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#62]
The Goods "Search" feature doesn't currently work properly for multi-word goods but the search results are not in alphabetical order for goods. If you enter "Silk" the list says Silk Fabric, Silk Thread, and Silk Cocoons. "Silk Cocoons" should be the first item in the list.

**Comment by aquilent-dgemoets** [comment]
This isn't a Search issue; it's an XML-generation issue.  The Silk goods are in the wrong order in the Goods list in the app-- Search does not change the order.

The XML generator should ensure that goods are in the correct alphabetical order.

**Comment by jfc3-dol** [comment]
Do we want to leave this open to see if ILAB can create an updated file at some point to correct the order? If not I can close this issues.

**Comment by aquilent-dgemoets** [comment]
Yes-- it's still an issue that should be fixed.

**Comment by aquilent-dgemoets** [comment]
This is fixed in the latest beta (9/9/16).  Please confirm then close the issue.

**Comment by nmangu** [comment]
This is validated in QA and is passed. 

![img_0045 1](https://cloud.githubusercontent.com/assets/10868918/18633089/a4343944-7e48-11e6-9c7f-a7d1b3fa5312.PNG)
