### ISSUE TITLE
Accessibility - Symbol Not read by VoiceOver

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#63]
While reading the Cameroon "Legal Standards" screen VoiceOver never read the ‡ symbol on the page near the "YES" in the footnotes. Please check that it also reads it on other places in the page too.

**Comment by aquilent-dgemoets** [comment]
Duplicate of #56 .

**Comment by jfc3-dol** [comment]
Closing this issue because it's a duplicate.
