### ISSUE TITLE
Recommendation - VoiceOver Reads "No." Incorrectly as "No" Instead of "Number"

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#64]
The Enforcement screen has the word "No." which VoiceOver reads as "No" when it is meant to be a number such as "number of people" instead of "no of people". Having it this way can be confusing to screen reader user.

**Comment by aquilent-dgemoets** [comment]
Duplicate of #57 .

**Comment by jfc3-dol** [comment]
Closing this issue because it's a duplicate.
