### ISSUE TITLE
Accessibility - Possible Colorblindness Issues with Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#66]
The "Yes" and "No" text on the "Legal Standards", "International Conventions", and "Other Mechanisms" screens uses color (red and green) to denote information that a person that has color blindness issues could have trouble figuring out the differences. If all the "No" answers are always red, and all the "Yes" answers are always green, then it shouldn't matter as much.

If you place  text in the "About This App" screen as you stated in our e-mail and each screen that either has the symbols or and asterisks in the footer of the screen you should be okay because it will help the user understand why some "Yes" responses are red and others are green..

**Comment by aquilent-dgemoets** [comment]
Green values are always Yes.  Red values are always either "No", "Yes*", or (in the case of Tokelau) "Unknown".  It is just meant to draw attention to a "bad" value.  But color is never used as the only means of conveying information, which is what the [design guide guards against](https://section508.gov/content/design-guide#1194.21i).

ILAB has already decided that Legal Standards will have the color-coding, but Enforcement will not.  It has not decided whether to remove the color-coding of "International Conventions" and "Other Mechanisms."

**Comment by jfc3-dol** [comment]
That works for me that they have the * (asterisks) along with the different color. 

If you want you can close this issue or I can.

**Comment by aquilent-dgemoets** [comment]
I didn't think I was "authorized" to close issues, even duplicates.  I was deferring to DOL/OPA.

**Comment by jfc3-dol** [comment]
Okay, I will close this issue then since I'm the one that opened them and I'm good with the explanation.
