### ISSUE TITLE
Missing Country Flags

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#67]
After finding two flags missing on the Countries screen for the Android application I check to see if they were missing on the iOS application and only the "West Bank & Gaza Strip" flag was missing.

**Comment by aquilent-dgemoets** [comment]
On my iOS simulator, both Western Sahara and West Bank & Gaza Strip flags are missing.  However, I believe that is intended behavior.  We will verify with ILAB.

**Comment by aquilent-dgemoets** [comment]
I've verified with ILAB that this is working as intended:  there should be no flags for Western Sahara and West Bank & Gaza Strip.

Related, there should be no country maps for:
•         Anguilla
•         British Virgin Islands
•         Christmas Island
•         Cocos (Keeling) Islands
•         Cook Islands
•         Falkland Islands (Islas Malvinas)
•         Montserrat
•         Niue
•         Norfolk Island
•         Saint Helena, Ascension, and Tristan
•         Tokelau
•         Western Sahara; and
•         West Bank & Gaza Strip.

I think we can close this issue.

**Comment by jfc3-dol** [comment]
Okay, with me if that is the way it is meant to be for both iOS and Android. Wanted to point it out in case they were supposed to be.

**Comment by jfc3-dol** [comment]
Should we leave these open to remind people that the flags need to be added when they are available or I can close this issue?

**Comment by aquilent-dgemoets** [comment]
There is no plan or intention for the flags to be made available, nor the maps for the listed island countries.
If this changes in subsequent years, then it will be an issue if they're still missing.

**Comment by jfc3-dol** [comment]
Okay, I will close this issue then?
