### ISSUE TITLE
Some lines are being skipped by VoiceOver

### ISSUE THREAD

**Issue by aquilent-dgemoets** [USDepartmentofLabor/Child-Labor#68]
As of the beta from 9/9, some lines in the Legal Standards and Enforcement screens are being skipped by VoiceOver.

For example, "Free Public Education,"  second and third lines of "Training for Labor Inspections section, and others.

**Comment by aquilent-dgemoets** [comment]
This appears only to happen on iOS 8.x, although this hasn't been confirmed.

**Comment by jfc3-dol** [comment]
It works for us on our iPad Air 2 with iOS version 9.3.4.

If you want to close you can.

**Comment by aquilent-dgemoets** [comment]
I think it should stay open because it is still an issue on some devices.  However, it's also probably not something we should try to fix at this point, unless there's time post-release (e.g., post-9/30).

**Comment by jfc3-dol** [comment]
After randomly check different countries I don't seem to see this as an issue.

Closing the issue.
