### ISSUE TITLE
More Info Screen - Difficult to Read the Businesses Screen Font is to Small

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#81]
Page/PDF's hard to read. VoiceOver is not reading any of what you would think are  headings in the document. Plus, the text is small and difficult to read.

**Comment by carolynhuang** [comment]
Is this referring what is linked under "NEW: Toolkit for Businesses"? The previous PDF was removed. We will request "ComplyChain" and "Install" font sizes be increased.

**Comment by jfc3-dol** [comment]
@carolynhuang,

All text on the "Toolkit for Businesses" screen is to small and difficult to read.

See screenshots from our iPad even at the larger screen size.

iPhone size

![sweat an dtoil - ios - toolkit for businesses screen text if iphone size](https://user-images.githubusercontent.com/10423487/30074645-4688f78c-9240-11e7-8e8e-42514abc15a3.png)

iPad size

![sweat an dtoil - ios - toolkit for businesses screen text if ipad size](https://user-images.githubusercontent.com/10423487/30074662-4d85085a-9240-11e7-9999-b352522fa9d0.png)

**Comment by carolynhuang** [comment]
That PDF is no longer in the app as of last week's version.  The link is now a URL which will allow users to download ComplyChain from Google Play or iTunes.

**Comment by jfc3-dol** [comment]
@carolynhuang.

Will check this tomorrow once I get my devices updated. I have been reviewing the website in Chrome today and waiting for the next version of the software that I thought was coming today at some point before going to deep into the testing to make sure things have been corrected.

**Comment by carolynhuang** [comment]
Thanks. Just to confirm - Has Giri pushed last week's version to Testflight for you? That is the latest version. There will not be another prior to publishing.

**Comment by jfc3-dol** [comment]
@carolynhuang,

@giridhar has pushed the application to Testflight as far as I know for everyone. But he places it on our devices for us so we can test. It's the way we have been doing it for years before he got here. I guess the thinking was it would be as if people downloaded it from the web. Plus, he has a device or two to do some quick testing to make sure it doesn't crash, but he was working from home Friday.

**Comment by giridhar** [comment]
@jfc3-dol yes we have pushed a new build on Friday.

**Comment by jfc3-dol** [comment]
Thanks, @giridhar for the update.

**Comment by carolynhuang** [comment]
Please close out on this issue. PDF no longer exists - was replaced by a link to download the Comply Chain app.

**Comment by jfc3-dol** [comment]
Looks like it's been removed.

Closing issue.
