### ISSUE TITLE
Countries - Legal Standards - Screen has Confusing Text on Top of Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#84]
Why is the following text bold and at the top of the screen "* Meets International Standards"? My guess is this should be at the bottom of the screen as a footnote like the other similar text. Or is it supposed to be a heading level one in the Markdown code?

Examples of this issue can be found in the following countries:
- Argentina
- Brazil
- India
- Haiti
- Jamaica
- Uganda

**Comment by carolynhuang** [comment]
The text is at the top of the screen because the user should see that the Yes/No's correspond to the question, "Meets International Standard." (As the user scrolls down the page, the design is clearer.) We will move the asterisk so that it is clear this text is not meant to be a footnote.

**Comment by jfc3-dol** [comment]
@carolynhuang,

Thanks, will check to see that this has been corrected in the next version of application or not.

Please make similar update if necessary to the Android version too.

**Comment by carolynhuang** [comment]
This should be resolved - please close this issue.  Asterisk is moved to the end of the header so reader knows it is a header with clarifying footnote.

**Comment by jfc3-dol** [comment]
Looks good to me now.

Closing issue,
