### ISSUE TITLE
Countries - Enforcement - Labor Tab - Gap in Layout

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#85]
Why is there a gap with gray text where you would assume a heading should be after the "Conducted" item under the "Unannounced Inspections" section?

Examples of this issue can be found in the following countries:
- Argentina
- Brazil
- India
- Haiti
- Jamaica
- Uganda

**Comment by carolynhuang** [comment]
These were deliberately done because no clear category could be found to title the sections. This year, you will see that we replaced blank gray bars with "Referral Mechanisms" and "Other Data." Please close this issue.

**Comment by jfc3-dol** [comment]
Thanks, for the clarification. I wanted to make sure a heading was not missed for some reason.

I'm closing issue then.
