### ISSUE TITLE
Goods - Bricks - VoiceOver Reading Visually Disabled Content

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#89]
After choosing to show only countries that have "Forced Labor" screen changes number of all countries from 18 to 7. When that happens, the countries that don't have "Forced Labor" are dimmed to look like they are not available. But VoiceOver still reads each country as a button. A few countries that are disabled are Argentina, Brazil, and Iran (not the full list). I can't activate them. Why not remove them from the list altogether if they do not apply to my choice.

**Comment by jfc3-dol** [comment]
Now VoiceOver is only reading the items that were selected and not the disabled one. 

BUT reviewing bricks and the "Child Labor"only type items VoiceOver reads the "Child Labor" items as "Button". Doesn't state which kind of labor it is like the other ones do.

**Comment by sanganalakshay** [comment]
Can you please clarify the issue.  When at Bricks|Child Labor screen, the VoiceOver reads Country|Labor Type|Button, and it does so for each country that is active.  We are not sure what the issue is here.

**Comment by jfc3-dol** [comment]
After choosing Bricks and then only Child Labor from the list of labor types VoiceOver reads those four items as "Button" and which one of the group of four it is.

On checking this a second and a third time the problem seems to be fixed.

**Comment by jfc3-dol** [comment]
Seems to be working and closing it now.
