### ISSUE TITLE
About This App - Remove Rubik's Cube Link

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor#95]
While double checking the remaining open issues, I noticed the "Methodology" screen had the heading level two (h2) text fixed and was working correctly with TalkBack. So I then checked the "About This App" screen too. 

When I got the bottom of the screen I noticed in the last sentence "easily" was spelled wrong as "esily". Upon further reading of the final paragraph, I saw the text is about Rubik's Cube and has a link.

@giridhar and I looked at the code, and the link was added with this last push of code.

Please remove it and double check there is no other code similar to on other screens. It seems extremely odd to add that in. 

Here is the link to the iOS "About This App" screen - https://github.com/USDepartmentofLabor/Child-Labor/blob/master/Child%20Labor/aboutthisapp.html

Here is the link to the commit of the code - https://github.com/USDepartmentofLabor/Child-Labor/commit/0ec13752a4b68a642cd3608881cb190f83dd73df#diff-1ea103615e0cd5645a55333b164114fb

Plus, the link goes to a weirdly spelled version of Rubik's ( ruwix ).

**Comment by sanganalakshay** [comment]
This issue has been addressed in the latest push on Nov 21 . https://github.com/USDepartmentofLabor/Child-Labor/commit/1b262dd321bbc0daee4ca9fe6ccf5ec3f8225741

**Comment by jfc3-dol** [comment]
@sanganalakshay,

Thanks, for making the update.

Has the change been merged so it can be pulled and recompiled?

Are there any other odd pieces of code you found?

I will check that it is removed once I have it on my devices and then close the issue.

**Comment by sanganalakshay** [comment]
@jfc3-dol  
I removed the odd piece of code about Rubik's cube and pushed the final version of code to the Master branch

**Comment by jfc3-dol** [comment]
Thanks, @sanganalakshay I will get our tech team to put the code on our devices.

**Comment by jfc3-dol** [comment]
@sanganalakshay,

Checked the "About This App" screen and the Rubik's cube text and link have been removed from the bottom of the screen.

I'm going to close this issue.
